services:
  ftp-server:
    container_name: my-ftp-server
    environment:
      - FTP_PASS=Shaastra_welcomes_you
      - FTP_USER=CTFadmin
    image: garethflowers/ftp-server
    ports:
      - '20-21:20-21/tcp'
      - '40000-40009:40000-40009/tcp'
    volumes:
      - '/data:/home/user'
